language: node_js    // Lenguaje que se va a testear
node_js:                    // versiones del lenguaje que se va a testear, puede ser más de una. 
	- "stable"         // por ejemplo esta versión 
