language: node_js
node_js:
  - "6.11.2"
-install:
  - npm install
  - npm install mocha --save-dev
  - npm install istanbul --save-dev
-script:
  - npm test
after_success:
  - npm run coveralls
addons:
  artifacts:
    paths:
      - ./mocha.js
